# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-18 21:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PuntoventaCarrito',
            fields=[
                ('id_carrito', models.AutoField(db_column='ID_CARRITO', primary_key=True, serialize=False)),
                ('cantidad_producto', models.IntegerField(db_column='CANTIDAD_PRODUCTO')),
                ('total', models.FloatField(db_column='TOTAL')),
            ],
            options={
                'db_table': 'PUNTOVENTA_CARRITO',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PuntoventaCategoria',
            fields=[
                ('id_categoria', models.AutoField(db_column='ID_CATEGORIA', primary_key=True, serialize=False)),
                ('nombre_categoria', models.CharField(blank=True, db_column='NOMBRE_CATEGORIA', max_length=50, null=True)),
            ],
            options={
                'db_table': 'PUNTOVENTA_CATEGORIA',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PuntoventaCorteCaja',
            fields=[
                ('id_corte_caja', models.AutoField(db_column='ID_CORTE_CAJA', primary_key=True, serialize=False)),
                ('total_recaudado', models.FloatField(db_column='TOTAL_RECAUDADO')),
                ('fecha_corte', models.DateField(db_column='FECHA_CORTE')),
            ],
            options={
                'db_table': 'PUNTOVENTA_CORTE_CAJA',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PuntoventaHistoriaInventario',
            fields=[
                ('id_historia_inventario', models.AutoField(db_column='ID_HISTORIA_INVENTARIO', primary_key=True, serialize=False)),
                ('fecha_registro', models.DateField(db_column='FECHA_REGISTRO')),
                ('cantidad_anterior', models.IntegerField(db_column='CANTIDAD_ANTERIOR')),
                ('cantidad_adicionada', models.IntegerField(db_column='CANTIDAD_ADICIONADA')),
                ('cantidad_nueva', models.IntegerField(db_column='CANTIDAD_NUEVA')),
            ],
            options={
                'db_table': 'PUNTOVENTA_HISTORIA_INVENTARIO',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PuntoventaProducto',
            fields=[
                ('id_producto', models.AutoField(db_column='ID_PRODUCTO', primary_key=True, serialize=False)),
                ('id_codigo_barra', models.CharField(blank=True, db_column='ID_CODIGO_BARRA', max_length=50, null=True)),
                ('nombre_producto', models.CharField(blank=True, db_column='NOMBRE_PRODUCTO', max_length=100, null=True)),
                ('precio_venta', models.FloatField(blank=True, db_column='PRECIO_VENTA', null=True)),
                ('precio_compra', models.FloatField(blank=True, db_column='PRECIO_COMPRA', null=True)),
                ('cantidad_disponible', models.IntegerField(blank=True, db_column='CANTIDAD_DISPONIBLE', null=True)),
                ('codigo_producto', models.CharField(blank=True, db_column='CODIGO_PRODUCTO', max_length=50, null=True)),
            ],
            options={
                'db_table': 'PUNTOVENTA_PRODUCTO',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PuntoventaVenta',
            fields=[
                ('id_venta', models.AutoField(db_column='ID_VENTA', primary_key=True, serialize=False)),
                ('fecha_venta', models.DateField(blank=True, db_column='FECHA_VENTA', null=True)),
                ('total_venta', models.FloatField(blank=True, db_column='TOTAL_VENTA', null=True)),
                ('pago_venta', models.FloatField(blank=True, db_column='PAGO_VENTA', null=True)),
                ('cambio_venta', models.FloatField(blank=True, db_column='CAMBIO_VENTA', null=True)),
            ],
            options={
                'db_table': 'PUNTOVENTA_VENTA',
                'managed': False,
            },
        ),
    ]
